[package]
name = "lead_lang_std"
version = "0.0.6"
edition = "2021"
description = "Standard Package of the Lead Programming Language"
license = "MIT"

[lib]
name = "lead_std"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inquire = "0.7.1"
lead_lang_interpreter = { path = "../../interpreter" }
