[package]
name = "lead_cli"
version = "0.0.5"
edition = "2021"

[[bin]]
name = "lead"
path = "./src/main.rs"

[dependencies]
lead_lang_interpreter = { path = "../interpreter" }
inquire = "0.7.1"
clap = { version = "4.4.18", features = ["derive"] }
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
libloading = "0.8.1"
