[package]
name = "lead_lang_core"
version = "0.0.6"
edition = "2021"
description = "Core Package of the Lead Programming Language"
license = "MIT"

[lib]
name = "lead_core"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lead_lang_interpreter = { path = "../../interpreter" }
