[package]
name = "leadman"
version = "0.1.0"
edition = "2021"
publish = false
rust-version = "1.81"

[dependencies]
chalk_rs = "1.0.1"
chrono = "0.4.38"
dirs = "5.0.1"
inquire = "0.7.5"
reqwest = { version = "0.12.9", features = ["json"] }
serde = { version = "1.0.215", features = ["derive"] }
tokio = { version = "1.41.1", features = ["rt", "rt-multi-thread", "macros"] }

[target.'cfg(windows)'.dependencies]
winreg = "0.52.0"
