[package]
name = "lead_docs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tao = { version = "0.26.2", features = ["rwh_06"] }
wry = "0.38.2"
