rustflags = []

[target.x86_64-unknown-freebsd]
linker = "clang"
rustflags = [
  "-C",
  "link-arg=--target=x86_64-unknown-freebsd",
  "-C",
  "link-arg=-fuse-ld=lld",
  "-C",
  "target-feature=+crt-static",
]

[target.x86_64-unknown-netbsd]
linker = "clang"
rustflags = [
  "-C",
  "link-arg=--target=x86_64-unknown-netbsd",
  "-C",
  "link-arg=-fuse-ld=lld",
  "-C",
  "target-feature=+crt-static",
]

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
